spring:
  application:
    name: service-customer

  datasource:
    url: jdbc:postgresql://postgresql-steve.alwaysdata.net/steve_customers
    username: steve
    password: 6Hpc4i!wrGReTmS

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        auto_quote_keyword: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /api-docs